m88 c++ code fix for clang 16.0.6 and libstdc++ 13.1.1
Actual error:

[720/1146] compile ../../src/utils/SkParseColor.cpp
FAILED: obj/src/utils/libskia.SkParseColor.o
/usr/bin/clang++ -MD -MF obj/src/utils/libskia.SkParseColor.o.d -DNDEBUG -DSKIA_DLL -DSK_R32_SHIFT=16 -DSK_GAMMA_APPLY_TO_A8 -DGR_OP_ALLOCATE_USE_NEW -DSKIA_IMPLEMENTATION=1 -DSK_GL -DSK_SUPPORT_PDF -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_USE_LIBGIFCODEC -DSK_CODEC_DECODES_PNG -DSK_ENCODE_PNG -DSK_CODEC_DECODES_RAW -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_WEBP -DSK_XML -I../.. -I../.. -I../../third_party/externals/libgifcodec -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -Wno-sign-conversion -Wno-unused-parameter -std=c++17 -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../src/utils/SkParseColor.cpp -o obj/src/utils/libskia.SkParseColor.o
../../src/utils/SkParseColor.cpp:300:39: error: no matching function for call to 'begin'
    const auto rec = std::lower_bound(std::begin(gColorNames),
                                      ^~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/initializer_list:88:5: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'const char *const *'
    begin(initializer_list<_Tp> __ils) noexcept
    ^
../../src/utils/SkParseColor.cpp:301:39: error: no matching function for call to 'end'
                                      std::end  (gColorNames),
                                      ^~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/initializer_list:99:5: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'const char *const *'
    end(initializer_list<_Tp> __ils) noexcept
    ^
../../src/utils/SkParseColor.cpp:307:16: error: no matching function for call to 'end'
    if (rec == std::end(gColorNames) || 0 != strcmp(name, *rec)) {
               ^~~~~~~~
/usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/initializer_list:99:5: note: candidate template ignored: could not match 'initializer_list<_Tp>' against 'const char *const *'
    end(initializer_list<_Tp> __ils) noexcept
    ^
3 errors generated.