Bump build host to fc44
Incompatibility with fc42:
skia/out/Release/libskunicode_icu.a depends on /usr/lib64/libicuuc.so.76,
while fc44 ships /usr/lib64/libicuuc.so.77.

Error: Failed to load with missing symbol "ubrk_next_76".

libicu's symbols are versioned by:
U_ICU_ENTRY_POINT_RENAME() in /usr/include/unicode/